<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE videojuego [
<!ELEMENT videojuego (identificador,nombre,fecha_de_creacion,nota,programadores,compañia,codigo_html_videojuego?)>
<!ELEMENT identificador (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_de_creacion (#PCDATA)>
<!ELEMENT nota (#PCDATA)>

<!ELEMENT programadores (programador+)>

<!ELEMENT programador (nombre,apellidos,DNI,fecha_de_nacimiento,direccion)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT DNI (#PCDATA)>
<!ELEMENT fecha_de_nacimiento (#PCDATA)>

<!ELEMENT direccion (tipo_de_via,nombre_de_via,codigo_postal,pais)>
<!ELEMENT tipo_de_via (#PCDATA)>
<!ELEMENT nombre_de_via (#PCDATA)>
<!ELEMENT codigo_postal (#PCDATA)>
<!ELEMENT pais (#PCDATA)>

<!ELEMENT compañia (nombre, NIF,direccion)>
<!ELEMENT NIF (#PCDATA)>
<!ELEMENT codigo_html_videojuego (#PCDATA)>

<!ATTLIST videojuego id ID #REQUIRED>
<!ATTLIST programador id ID #REQUIRED>
<!ATTLIST compañia id ID #REQUIRED>


]>



<videojuego id="b1">
    <identificador> 123 </identificador>
    <nombre> Black Ops 3 </nombre>
    <fecha_de_creacion> 2015 </fecha_de_creacion>
    <nota> 10 </nota>
<programadores>
    <programador id ="p1">
        <nombre> Aaron </nombre>
        <apellidos> Gutierrez Gomez </apellidos>
        <DNI> 56783495P </DNI>
        <fecha_de_nacimiento> 12/5/98 </fecha_de_nacimiento>
        <direccion> 
            <tipo_de_via> Avenida </tipo_de_via>
            <nombre_de_via> Via Lactea </nombre_de_via>
            <codigo_postal> 25486 </codigo_postal>
            <pais> España </pais>
        </direccion>
    </programador>

    <programador id ="p2">
        <nombre> Diego </nombre>
        <apellidos> Hernandez Perez </apellidos>
        <DNI> 52796472Ñ </DNI>
        <fecha_de_nacimiento> 5/04/05 </fecha_de_nacimiento>
        <direccion> 
            <tipo_de_via> Calle </tipo_de_via>
            <nombre_de_via> Portugal </nombre_de_via>
            <codigo_postal> 22478 </codigo_postal>
            <pais> España </pais>
        </direccion>
    </programador>
</programadores>

    <compañia id ="p3"> 
    <nombre> Treyacrh </nombre>
    <NIF> 81487634Z </NIF>
    <direccion> 
            <tipo_de_via> Avenida </tipo_de_via>
            <nombre_de_via> Carlos III </nombre_de_via>
            <codigo_postal> 29785 </codigo_postal>
            <pais> España </pais>
        </direccion>
    </compañia>


<codigo_html_videojuego>
    <![CDATA[ 
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Black Ops 3</title>
</head>
<body>
    <h1 style="text-align: center;"> BIENVENIDO</h1>
    <h2 style="text-align: center; color: red;"> Black Ops 3</h2>
    <img src="https://th.bing.com/th/id/R.c104c40536551b83cc925e05904aab17?rik=TBH6sdsRiQiEKw&riu=http%3a%2f%2fhdqwalls.com%2fwallpapers%2f2016-call-of-duty-black-ops-3.jpg&ehk=%2f3Ji9rvAK1UhCyWD9s9Om40kBF9t72YUtb9AOqovuH4%3d&risl=1&pid=ImgRaw&r=0" alt="Imagen Logo BO3">
</body>
</html>
    ]]>
</codigo_html_videojuego>
</videojuego>
